version: '3'

services:
  app:
    # Use the container image built from the specified Dockerfile;
    # as opposed to a container image available on DockerHub.
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      # Map a host port (by default, 8000, but it can be overridden via an
      # environment variable) to port 8000 of the container; the latter being
      # the port on which the MkDocs dev-server listens by default.
      #
      # The environment variable can be specified either via an `.env` file,
      # or by defining it when invoking `docker compose`, like this:
      # ```
      # DOCS_PORT=1234 docker compose up
      # ```
      #
      - "${DOCS_PORT:-8000}:8000"
    volumes:
      # Mount the root directory of the repository, at `/nmdc-schema` within the container.
      #
      # Note: This will overwrite any `/nmdc-schema` directory that might have been created
      #       while building the container (i.e. while processing the `Dockerfile`).
      #
      - "./:/nmdc-schema"
