name: Berkeley Schema Change
description: Describe all PRs for changes during berkeley-schema freeze
title: "[berkeley-schema] <title>"
body:
  - type: markdown
    attributes:
      value: |
        # Guidelines
        
        ## _Light_ Schema Freeze
        The nmdc-schema and berkeley-schema are under a light freeze this means changes **should not** be made that have any down stream implications. 
        To ensure this, PRs need to be closely reviewed with **every** component of the NMDC in mind.
        
        ## Reviewers
        To ensure no changes are made unexpectedly, ALL berkeley-schema refacror roll out task coordinators should be listed as reviewrs for ALL PRs. 
        See [squad proposal](https://docs.google.com/document/d/1XXN1YuaBuSkxPXeiLKm5YxYzXTamBPQrzzeLhlh7PWs/edit#heading=h.u52g8v319adh) for list of names.
        PRs should NOT be merged until they have been approved by all task coordinators.
  - type: checkboxes
    attributes: 
      label: What type of PR is this?
      description: Select all applicable options to catagorize this PR. 
      options:
        - label: Refactor
        - label: Feature
        - label: Bug Fix
        - label: Optimization
        - label: Documentation Update
        - label: Content change (Ex- slot or Class name, slot multiplicity changes, slot movement from one Class to another, creating a new slot/Class, Enum value changes)
        - label: Informitive change (Ex- descriptions of slots, classes, or enums, removal of unused, commented, or invalid code, updated mappings of terms, classes, or slots to ontologies, added an additional Enum to accommodate new or future metadata)
        - label: changes to ANY files in /src/schema
  - type: textarea
    attributes:
      label: Description
      description: PRs should be small and concise
      value: "Provide a description of the PR."
    validations:
      required: true
  - type: input
    attributes:
      label: Issues
      description: What issues are part of this PR?
      placeholder: ex. /issues/issues/100, nmdc-schema/issues/400
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Added or Updated tests & example files?
      description: Yes or no, if you added or changed any test or example files
      options:
        - label: Yes
        - label: No
        - label: I need help with writing tests
      - type: textarea
        attributes:
          label: If no, why
          description: Provide why no examples or tests were updated or added
          value: "This is why I have no tests or example files."


      
  
  
  
  
  
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  


