name: Check Pull Request

# Controls when the action will run. Triggers the workflow on pull requests.
on:
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: trigger-check-pull-request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - name: Checkout
      uses: actions/checkout@v2
    
    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    # Install pipenv
    - name: Install pipenv
      run: python3 -m pip install pipenv
        
    # Install dependencies
    #- name: Install dependencies
    #  run: pipenv install -d
        # pip install --upgrade pip
        # pip install pipenv
        # pip install linkml

    # Load pipenv from cache
    # see: https://github.com/actions/cache/blob/main/examples.md#python---pipenv
    - name: Load pipenv from cache
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
    
    # Excute the Makefile to build generated artifacts
    - name: Make Artifacts
      run: |
        make all
        # make stage-jsonschema
        # make stage-python
        
    # Validate json schema aganst test data
    - name: Validate JSON Schema
      run: |
        make test-jsonschema
