name: Auto-deployment of nmdc-schema Documentation
on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Poetry.
        uses: snok/install-poetry@v1.3

      - name: Install dependencies.
        # Note: The `-E docs` option tells Poetry we want it to install the packages listed
        #       in the "docs" list in the `tool.poetry.extras` section of `pyproject.toml`.
        #       Reference: https://python-poetry.org/docs/main/pyproject#extras
        run: poetry install -E docs

      - name: Compile derivative files from source
        # Note: `refgraph` requires a YAML file that gets generated here.
        run: |
          make squeaky-clean all

      - name: Generate web-based documentation
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc

      - name: Generate interactive schema visualizations
        # Reference: https://github.com/microbiomedata/refscan
        run: |
          pipx install "refscan>=0.1.20,<1.0.0"
          refgraph --schema nmdc_schema/nmdc_materialized_patterns.yaml --subject collection --graph docs/collection-graph.html
          refgraph --schema nmdc_schema/nmdc_materialized_patterns.yaml --subject class --graph docs/class-graph.html

        # Deploy the docs to GitHub Pages.
        #
        # Note: The `make mkd-gh-deploy` command below uses the `mkd-%` target
        #       defined in `Makefile`. That target's action (i.e. recipe)
        #       strips off the `mkd-` prefix and passes the rest of the command
        #       to `$ poetry run mkdocs`, effectively translating the command
        #       below into `$ poetry run mkdocs gh-deploy`.
        #
        # Reference: https://www.mkdocs.org/user-guide/deploying-your-docs/
        #
      - name: Deploy web-based documentation to GitHub Pages
        run: |
          make mkd-gh-deploy
