name: migration-with-java-action
on: workflow_dispatch
# wget AND curl?!
# combine run statements
jobs:
  migration-with-java-job:
    runs-on: ubuntu-latest
    steps:
      #      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: wget https://github.com/ontodev/robot/releases/download/v1.9.5/robot.jar
      - run: wget https://raw.githubusercontent.com/ontodev/robot/master/bin/robot
      - run: sudo chmod u+x robot
      - run: ./robot --version
