name: action-1
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      #      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: step-1
        run: echo "Hello World!"
      - run: java --version
      - run: wget https://github.com/ontodev/robot/releases/download/v1.9.5/robot.jar
      - run: ls -l robot.jar
      - run: curl https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot
      - run: sudo chmod u+x robot
      - run: ls -l robot
