name: Preview documentation build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Install dependencies
        run: poetry install -E docs

      - name: Compile derivative files from source
        run: |
          make squeaky-clean all

      - name: Generate web-based documentation
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          poetry run mkdocs build -d site

      - name: Generate interactive schema visualizations
        run: |
          pipx install "refscan>=0.1.20,<1.0.0"
          refgraph --version
          refgraph --schema nmdc_schema/nmdc_materialized_patterns.yaml --subject collection --graph site/collection-graph.html
          refgraph --schema nmdc_schema/nmdc_materialized_patterns.yaml --subject class --graph site/class-graph.html
          head -10 site/collection-graph.html
          head -10 site/class-graph.html

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site/
          preview-branch: gh-pages
