name: Preview documentation build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency: preview-${{ github.ref }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Install dependencies
        run: poetry install -E docs

      - name: Derive files from sources
        # Note: First, we replace the "0.0.0" placeholder version number in `pyproject.toml`.
        # Reference: https://github.com/mtkennerly/poetry-dynamic-versioning/blob/master/README.md#command-line-mode
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry dynamic-versioning
          make squeaky-clean all

      - name: Generate web-based documentation
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          poetry run mkdocs build -d site

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site/
          preview-branch: gh-pages
